# Generated by Django 4.0.4 on 2022-04-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_nome_pedidos_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='mesa',
            field=models.TextField(),
        ),
    ]
